## 1. Multiples of 3 and 5

Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
def mut_3_5(n):
    l = []
    for i in range(n):
        if i%3 == 0:
            l.append(i)
        elif i%5 == 0:
            l.append(i)
    return sum(l)

In [2]:
n = 1000
mut_3_5(n)

233168

In [3]:
n = 10
mut_3_5(n)

23

## 2. Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [5]:
def even_fibonacci(n):
    if (n <= 0):
        return 0
    
    fib = [0] * (n+1)
    fib[1] = 1
    
    s = fib[0] + fib[1]
    
    for i in range(2, n+1):
        fib[i] = fib[i-1] + fib[i-2]
        s = s + fib[i]
    
    even_fib = []
    for i in fib:
        if i%2 == 0:
            even_fib.append(i)
    print(even_fib)        
    return s

In [6]:
n = 31
even_fibonacci(n)

[0, 2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040]

3524577

## 3. Largest prime factor

Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

### Method - 1

In [8]:
# def isPrime( value ):
#     for i in range( 2, value ):
#         if value % i == 0:
#             return False
#     return True

# def LargestPrimeFactor ( value ):
#     result = []
#     for i in range( 2, value ):
#         if isPrime( i ):
#             if value % i == 0:
#                 result.append( i )
#     return result

# print( LargestPrimeFactor( 600851475143 ) )

### Method - 2

In [9]:

# Python3 code to find largest prime 
# factor of number 
import math 
  
# A function to find largest prime factor 
def maxPrimeFactors (n): 
      
    # Initialize the maximum prime factor 
    # variable with the lowest one 
    maxPrime = -1
      
    # Print the number of 2s that divide n 
    while n % 2 == 0: 
        maxPrime = 2
        n >>= 1     # equivalent to n /= 2 
          
    # n must be odd at this point,  
    # thus skip the even numbers and  
    # iterate only for odd integers 
    for i in range(3, int(math.sqrt(n)) + 1, 2): 
        while n % i == 0: 
            maxPrime = i 
            n = n / i 
      
    # This condition is to handle the  
    # case when n is a prime number  
    # greater than 2 
    if n > 2: 
        maxPrime = n 
      
    return int(maxPrime) 
  
# Driver code to test above function 
n = 13195
print(maxPrimeFactors(n)) 
  
n = 600851475143
print(maxPrimeFactors(n))

29
6857

## 4. Largest palindrome product

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

913 * 993 = 906609

In [10]:
def palindrome_number(start, end):
    p = []
    for i in range(start, end):
        for j in range(start, end):
            num = str(i*j)
            if num == num[::-1]:
                p.append(int(num)) 
    p.sort(reverse=True)
    return max(p)

In [11]:
start = 100
end = 1000
palindrome_number(start, end)

906609

In [12]:
start = 10
end = 100
palindrome_number(start, end)

9009

## 5. Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [13]:
def isMultiple(x, n):
    for i in range(1, n):
        if x % i != 0:
            return False
    return True

In [14]:
isMultiple(2520, 12)

False

In [15]:
def factorial(n):
    if n > 1: return n * factorial(n - 1)
    elif n >= 0: return 1
    else: return -1

In [16]:
factorial(20)

2432902008176640000

In [17]:
# returns smallest multiple that is evenly divisible by all numbers from 1 - n
# returns -1 if multiple does not exist
def findSmallestMultiple(n):
    for i in range(n, factorial(n) + 1, n):
        if isMultiple(i, n):
            return i
    return -1

# checks every number between 1 and n to see if x is a multiple of every number
# returns True if x is found to be a multiple of every number, and False if x is
# found to not be a multiple of any number
def isMultiple(x, n):
    for i in range(1, n):
        if x % i != 0:
            return False
    return True

# returns the n factorial, or -1 if it does not exist
def factorial(n):
    if n > 1: return n * factorial(n - 1)
    elif n >= 0: return 1
    else: return -1

print (findSmallestMultiple(10)) # 2520
print (findSmallestMultiple(20))

2520
232792560

## 6. Sum square difference
Problem 6

The sum of the squares of the first ten natural numbers is,

12+22+...+102=385

The square of the sum of the first ten natural numbers is,

(1+2+...+10)2=552=3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025âˆ’385=2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [18]:
1+4+9+16+25+36+49+64+81+100

385

In [19]:
# sum of the squares of the first ten natural numbers
def sum_squares(n):
    x = 0
    for i in range(1, n+1):
        x = i**2 + x 
    return x

In [21]:
sum_squares(10)

385

In [22]:
(1+2+3+4+5+6+7+8+9+10)**2

3025

In [23]:
# The square of the sum of the first ten natural numbers 
def square_sum(n):
    x = 0
    for i in range(1, n+1):
        x = i + x
    return x**2

In [25]:
square_sum(10)

3025

In [26]:
# the difference between the sum of the squares of the 
# first one hundred natural numbers and the square of the sum.
def diff_sum_squares_sum(n):
    return (square_sum(n) - sum_squares(n))


# sum of the squares of the first ten natural numbers
def sum_squares(n):
    x = 0
    for i in range(1, n+1):
        x = i**2 + x 
    return x  

# The square of the sum of the first ten natural numbers 
def square_sum(n):
    x = 0
    for i in range(1, n+1):
        x = i + x
    return x**2

In [27]:
diff_sum_squares_sum(10)

2640

In [28]:
diff_sum_squares_sum(100)

25164150

## 10001st prime 
Problem 7

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [29]:
def prime_or_not(n):    
    for i in range(2,n):
        if n%i == 0:
            return False
    return True

def prime_index(idx):
    l = []
    n = 1
    while (len(l) < idx):
        n = n + 1
        if prime_or_not(n):
            l.append(n)
    return n

In [30]:
prime_index(10001)

104743

## 8. Largest product in a series
Problem 8

The four adjacent digits in the 1000-digit number that have the greatest product are 9 Ã— 9 Ã— 8 Ã— 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [31]:
# for 4 digit

def largest_product(n):
    n = n.replace(" ", "")
    x = 0
    l = []
    while len(l) < (len(n)-3):
        x = x+1
        prod = int(n[x-1])*int(n[x])*int(n[x+1])*int(n[x+2])
        l.append(prod)
    l.sort(reverse=True)   
    return max(l)

In [32]:
n = "73167176531330624919225119674426574742355349194934 96983520312774506326239578318016984801869478851843 85861560789112949495459501737958331952853208805511 12540698747158523863050715693290963295227443043557 66896648950445244523161731856403098711121722383113 62229893423380308135336276614282806444486645238749 30358907296290491560440772390713810515859307960866 70172427121883998797908792274921901699720888093776 65727333001053367881220235421809751254540594752243 52584907711670556013604839586446706324415722155397 53697817977846174064955149290862569321978468622482 83972241375657056057490261407972968652414535100474 82166370484403199890008895243450658541227588666881 16427171479924442928230863465674813919123162824586 17866458359124566529476545682848912883142607690042 24219022671055626321111109370544217506941658960408 07198403850962455444362981230987879927244284909188 84580156166097919133875499200524063689912560717606 05886116467109405077541002256983155200055935729725 71636269561882670428252483600823257530420752963450"
largest_product(n)

5832

In [33]:
# for 13 digits

def largest_product(n):
    n = n.replace(" ", "")
    x = 0
    l = []
    while len(l) < (len(n)-13):
        x = x+1
        prod = int(n[x-1])*int(n[x])*int(n[x+1])*int(n[x+2])*int(n[x+3])*int(n[x+4])*int(n[x+5])*int(n[x+6])*int(n[x+7])*int(n[x+8])*int(n[x+9])*int(n[x+10])*int(n[x+11])
        l.append(prod)
    l.sort(reverse=True)   
    return max(l)

In [34]:
n = "73167176531330624919225119674426574742355349194934 96983520312774506326239578318016984801869478851843 85861560789112949495459501737958331952853208805511 12540698747158523863050715693290963295227443043557 66896648950445244523161731856403098711121722383113 62229893423380308135336276614282806444486645238749 30358907296290491560440772390713810515859307960866 70172427121883998797908792274921901699720888093776 65727333001053367881220235421809751254540594752243 52584907711670556013604839586446706324415722155397 53697817977846174064955149290862569321978468622482 83972241375657056057490261407972968652414535100474 82166370484403199890008895243450658541227588666881 16427171479924442928230863465674813919123162824586 17866458359124566529476545682848912883142607690042 24219022671055626321111109370544217506941658960408 07198403850962455444362981230987879927244284909188 84580156166097919133875499200524063689912560717606 05886116467109405077541002256983155200055935729725 71636269561882670428252483600823257530420752963450"
largest_product(n)

23514624000

In [35]:
# def largest_product(n, d_l):
#     n = n.replace(" ", "")
#     x = 0
#     l = []
#     t = 1
#     while len(l) < (len(n)-3):
#         for num in n[x:x+d_l]:
#             t = int(num)*t
#         l.append(t)
#         x = x+1
#     l.sort(reverse=True)   
#     return max(l)

In [36]:
# n = "73167176531330624919225119674426574742355349194934 96983520312774506326239578318016984801869478851843 85861560789112949495459501737958331952853208805511 12540698747158523863050715693290963295227443043557 66896648950445244523161731856403098711121722383113 62229893423380308135336276614282806444486645238749 30358907296290491560440772390713810515859307960866 70172427121883998797908792274921901699720888093776 65727333001053367881220235421809751254540594752243 52584907711670556013604839586446706324415722155397 53697817977846174064955149290862569321978468622482 83972241375657056057490261407972968652414535100474 82166370484403199890008895243450658541227588666881 16427171479924442928230863465674813919123162824586 17866458359124566529476545682848912883142607690042 24219022671055626321111109370544217506941658960408 07198403850962455444362981230987879927244284909188 84580156166097919133875499200524063689912560717606 05886116467109405077541002256983155200055935729725 71636269561882670428252483600823257530420752963450"
# largest_product(n,4 )

In [37]:
s = "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450"
     
largestProduct = 0

for i in range(0, len(s) - 13):

    product = 1

    for j in range(i, i + 13):
        product *= int(s[j: j + 1])

    if product > largestProduct:
        largestProduct = product

print (largestProduct)

23514624000

## 9. Special Pythagorean triplet 
Problem 9

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [38]:
def pythagorean_triplet():
    for i in range(1, 1001):
        for j in range(1, 1001):
            for k in range(1, 1001):
                if i<j<k:
                    if i+j+k == 1000:
                        if i**2+j**2 == k**2:
                            yield i*j*k

In [39]:
list(pythagorean_triplet())

[31875000]

In [40]:
for a in range(3, 1000):
    for b in range (a + 1, 999):
        cSquared = a**2 + b**2
        c = cSquared**0.5

        if a + b + c == 1000:
            product = a * b * c
            print(product)
            break

31875000.0

## 10. Summation of primes
Problem 10

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [41]:
# def prime_or_not(n):
#     for i in range(2,n):
#         if n%i == 0:
#             return False
#     return True

# prime or not using while loop

In [42]:
def prime_or_not(n):
    if n > 1:
        for i in range(2,int(n**0.5)+1):
            if (n%i) == 0:
                return False
        else:
            return True
    else:
        return False

In [43]:
prime_or_not(13)

True

In [44]:
prime_or_not(100000)

False

## method - 2 for finding prime or not

In [45]:
x = 5
if x > 1:
    for n in range(2, (x//2)+1):
        if (x % n) == 0:
            print(x, "is not prime")
            print(n, "times", x // n, "is", x)
            break
    else:
        print(x, "is a prime number")
else:
    print(x, "is not prime number")

5 is a prime number

## problem - 10
### Method - 1

In [46]:
def sum_prime(n):
    l = []
    for num in range(2,n+1):
        if prime_or_not(num):
            l.append(num)       
    return sum(l)

In [47]:
sum_prime(10)

17

In [48]:
sum_prime(2000000)

142913828922

## Using yield -  Method-2

In [49]:
def sum_prime(n):
    for num in range(2,n+1):
        if prime_or_not(num):
            yield num

In [50]:
sum_prime(10)

In [51]:
list(sum_prime(10))

[2, 3, 5, 7]

In [52]:
x = 0
for num in list(sum_prime(10)):
    x = num+x
print(x)

17

## Method - 3

In [53]:
# The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
# Find the sum of all the primes below two million.

# returns True if parameter n is a prime number, False if composite and "Neither prime, nor composite" if neither
def isPrime(n):
    if n < 2: return "Neither prime, nor composite"
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

sum = 0
for i in range(2, 2000000):
    if isPrime(i):
        sum += i

print (sum)

142913828922

## 11. Largest product in a grid  
Problem 11

In [54]:
def largest_product(g):
    a = g.split(sep=" ")
    s = []
    for i in range(0, len(a), 20):
        s.append(a[i:i+20])
        
    horizantal = []
    vertical = []
    diagonal_down = []
    diagonal_up = []
        
    # Horizantal
    for i in range(0, len(s)):
        for j in range(0, len(s)-3):
            horizantal.append(int(s[i][j])*int(s[i][j+1])*int(s[i][j+2])*int(s[i][j+3]))

    # vertical
    for i in range(0, len(s)-3):
        for j in range(0, len(s)):
            vertical.append(int(s[i][j])*int(s[i+1][j])*int(s[i+2][j])*int(s[i+3][j]))

    # diagonal_down        
    for i in range(0,len(s)-3):
        for j in range(0, len(s)-3):
            diagonal_down.append(int(s[i][j])*int(s[i+1][i+1])*int(s[i+2][i+2])*int(s[i+3][i+3]))        

    # diagonal_up
    for i in range(3, len(s)-3):
        for j in range(0, len(s)-3):
            diagonal_up.append(int(s[i][j])*int(s[i-1][j+1])*int(s[i-2][j+2])*int(s[i-3][j+3]))
       
    return max([max(horizantal), max(vertical), max(diagonal_down), max(diagonal_up)])

In [55]:
g = "08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48"
largest_product(g)

70600674

## Method - 2

In [56]:
grid=[8,2,22,97,38,15,0,40,0,75,4,5,7,78,52,12,50,77,91,8,
49,49,99,40,17,81,18,57,60,87,17,40,98,43,69,48,4,56,62,0,
81,49,31,73,55,79,14,29,93,71,40,67,53,88,30,3,49,13,36,65,
52,70,95,23,4,60,11,42,69,24,68,56,1,32,56,71,37,2,36,91,
22,31,16,71,51,67,63,89,41,92,36,54,22,40,40,28,66,33,13,80,
24,47,32,60,99,3,45,2,44,75,33,53,78,36,84,20,35,17,12,50,
32,98,81,28,64,23,67,10,26,38,40,67,59,54,70,66,18,38,64,70,
67,26,20,68,2,62,12,20,95,63,94,39,63,8,40,91,66,49,94,21,
24,55,58,5,66,73,99,26,97,17,78,78,96,83,14,88,34,89,63,72,
21,36,23,9,75,0,76,44,20,45,35,14,0,61,33,97,34,31,33,95,
78,17,53,28,22,75,31,67,15,94,3,80,4,62,16,14,9,53,56,92,
16,39,5,42,96,35,31,47,55,58,88,24,0,17,54,24,36,29,85,57,
86,56,0,48,35,71,89,7,5,44,44,37,44,60,21,58,51,54,17,58,
19,80,81,68,5,94,47,69,28,73,92,13,86,52,17,77,4,89,55,40,
4,52,8,83,97,35,99,16,7,97,57,32,16,26,26,79,33,27,98,66,
88,36,68,87,57,62,20,72,3,46,33,67,46,55,12,32,63,93,53,69,
4,42,16,73,38,25,39,11,24,94,72,18,8,46,29,32,40,62,76,36,
20,69,36,41,72,30,23,88,34,62,99,69,82,67,59,85,74,4,36,16,
20,73,35,29,78,31,90,1,74,31,49,71,48,86,81,16,23,57,5,54,
1,70,54,71,83,51,54,69,16,92,33,48,61,43,52,1,89,19,67,48]

largest=[0,0,0,0]

#horizontal and verticle

for h in range(0,20):
    for hsub in range(0,17):
        if grid[h*10+hsub]*grid[h*10+hsub+1]*grid[h*10+hsub+2]*grid[h*10+hsub+3] > largest[0]:
            largest[0] = grid[h*10+hsub]*grid[h*10+hsub+1]*grid[h*10+hsub+2]*grid[h*10+hsub+3]


        if grid[(hsub*20)+h]* grid[((hsub+1)*20)+h]* grid[((hsub+2)*20)+h]* grid[((hsub+3)*20)+h] > largest[1]:
            largest[1] = grid[(hsub*20)+h]* grid[((hsub+1)*20)+h]* grid[((hsub+2)*20)+h]* grid[((hsub+3)*20)+h]

#diagonal right and left

for r in range(0,17):
    for rsub in range (0,17):
        if grid[(rsub*20)+r]* grid[((rsub+1)*20)+1+r]* grid[((rsub+2)*20)+2+r]* grid[((rsub+3)*20)+3+r] > largest[2]:
            largest[2] = grid[(rsub*20)+r]* grid[((rsub+1)*20)+1+r]* grid[((rsub+2)*20)+2+r]* grid[((rsub+3)*20)+3+r] 

        if grid[(rsub*20)+3+r]* grid[((rsub+1)*20)+2+r]* grid[((rsub+2)*20)+1+r]* grid[((rsub+3)*20)+r] > largest[3]:
            largest[3] =  grid[(rsub*20)+3+r]* grid[((rsub+1)*20)+2+r]* grid[((rsub+2)*20)+1+r]* grid[((rsub+3)*20)+r]

print(max(largest))

70600674

## 12 Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [57]:
def factors(x):
    f = []
    for i in range(1, x+1):
        if x%i==0:
            f.append(i)
    return f

def highly_div_tri_num(l):
    seq_tri = [0,1]
    temp_length = 0
    while temp_length < l-1:
        x = seq_tri[-1]+seq_tri[-2]
        seq_tri.append(x)
        factors_length = len(factors(x))
        if factors_length > temp_length:
            temp_length = factors_length
    return x, seq_tri

In [58]:
highly_div_tri_num(7)

(144, [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144])